### PR TITLE
Eect00

### PR DESCRIPTION
**Pull request by prakharcode**

### CODE REVIEW

**Comment by prakharcode** [comment]
@helgee should I rebase this as well because I have already rebased #20 which builds on top of this.

**Comment by giordano** [comment]
I suspect you're rebasing "by hand", aren't you?  In git, you can [rebase](https://git-scm.com/book/it/v2/Git-Branching-Rebasing) on a branch with
```
$ git rebase <branch name>
```
If there are no conflicts, you don't have to do anything else.

I think it's better for the time being to leave this PR as it is, and fix it later.

**Comment by prakharcode** [comment]
Yes, I'm rebasing by pulling and merging, I've faced some problem with `git rebase` hence I tend to do rebasing in a bit manual way. Is that bad @giordano ?

**Comment by giordano** [comment]
It's not *bad*, it's just that you may be doing some extra work.  What kind of problems were you facing?  Consider that `rebase` rewrites history, that may be indeed the cause of some problems

**Comment by helgee** [comment]
@prakharcode In my book the best option is to do `git pull --rebase master` on the feature branch, see https://coderwall.com/p/7aymfa/please-oh-please-use-git-pull-rebase

@giordano do you have experience with that?

**Comment by helgee** [comment]
The code in this PR already slipped in (somehow). Closing.

**Pull request closed without merging**
